name: Build and Deploy Firebase Web Application
# Workflow Caller version: 3.0.0

on:
  push:
    branches:
      [master]
  pull_request:
  workflow_dispatch:
    inputs:
      use_preview_channel:
        description: 'Use preview channel?'
        required: false
        type: boolean
        default: false

jobs:
  call-global-iconica-workflow:
    uses: Iconica-Development/.github/.github/workflows/firebase-web-cd.yml@master
    secrets: inherit
    permissions: write-all
    with:
      gcp_sa_key_override: '(KEY TO BE USED WHEN IT IS NOT CALLED): GCP_SA_KEY'
      # pass a true value to use the preview channel for pull requests, use workflow_dispatch input, or default to false
      use_preview_channel: ${{ (github.event_name == 'pull_request' && true) || github.event.inputs.use_preview_channel == 'true' || false }}
      subfolder: '.' # add optional subfolder to run workflow in