name: Iconica Standard App CI Action

# Workflow version: 2.0.0

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
    workflow_call:

env:
    DOTENV_BASE64: ${{ secrets.DOTENV_BASE64 }}

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                cache: true
                cache-key: ${{ runner.OS }}-flutter-install-cache
            - name: Project preparation
              run: flutter pub get
            - name: Create dotenv and .env file from GitHub Secrets
              run: | 
                if [[ -n "${DOTENV_BASE64}" ]]; then
                    echo -n "${DOTENV_BASE64}" | base64 -d > dotenv
                    echo -n "${DOTENV_BASE64}" | base64 -d > .env
                else
                    touch .env
                    touch dotenv
                fi
              env:
                DOTENV_BASE64: ${{ env.DOTENV_BASE64 }}
            - name: Dart format
              run: dart format -o none --set-exit-if-changed .
            - name: Flutter analyze
              run: flutter analyze
            - name: Flutter test
              run: flutter test --coverage --reporter github --no-test-assets --exclude-tags integration

        