name: Iconica Standard Component Release Action
# Workflow version: 2.0.0

on:
    workflow_call:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: "stable"
                cache: true
                cache-key: ${{ runner.OS }}-flutter-install-cache

            - name: Check for melos.yaml
              id: melos-check
              run: |
                if [ -f melos.yaml ]; then
                  echo "::set-output name=melos::true"
                else
                  echo "::set-output name=melos::false"
                fi

            - name: Install Melos (if Melos project)
              if: steps.melos-check.outputs.melos == 'true'
              run: dart pub global activate melos

            - name: Bootstrap Melos (if Melos project)
              if: steps.melos-check.outputs.melos == 'true'
              run: melos bootstrap

            - name: Add pub server credentials
              env:
                PUB_SERVER_URL: ${{ vars.PUB_SERVER_URL }}
              run: |
                dart pub token add --env-var PUB_TOKEN $PUB_SERVER_URL

            - name: Publish packages for Melos project
              if: steps.melos-check.outputs.melos == 'true'
              env:
                PUB_TOKEN: ${{ secrets.PUB_TOKEN }}
              run: |
                melos exec -c 1 -- flutter pub publish --force || echo 'Skipping failed publish'
            - name: Publish single package for non-Melos project
              if: steps.melos-check.outputs.melos == 'false'
              run: flutter pub publish --force
              env:
                PUB_TOKEN: ${{ secrets.PUB_TOKEN }}
