name: Iconica Standard Scaleway container deployment
# Workflow version: 1.0.0

# Expects the following GitHub repository variables to be set:
# - CONTAINER_REGISTRY_ENDPOINT
# - SCW_PROJECT_ID
# - SCW_ORGANIZATION_ID
# - CONTAINER_ID
# - SCW_REGION

# Expects the following GitHub secrets to be set:
# - SCW_ACCESS_KEY
# - SCW_SECRET_KEY

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_call:
    inputs:
      subfolder:
        type: "string"
        description: "Subfolder where the container file is located (default=.)"
        required: false
        default: "."
      container_context:
        type: "string"
        description: "Subfolder where the container context is located (default=.)"
        required: false
        default: "."
      container_file:
        type: "string"
        description: "Name of the container file to build (default=Containerfile)"
        required: false
        default: "Containerfile"
      container_build_args:
        type: "string"
        description: "Additional build arguments to pass along while building the container (default=none)"
        required: false
        default: ""
      container_name:
        type: "string"
        description: "Name of the final container image"
        required: true
      container_version:
        type: "string"
        description: "Version of the final container image (default=latest)"
        required: false
        default: "latest"


jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Clone the code"
        uses: "actions/checkout@v7"

      # Build
      - name: "Build the container image"
        run: |
          cd ${{ inputs.subfolder }}
          docker build ${{ inputs.container_context }} \
            -f ${{ inputs.container_file }} \
            ${{ inputs.container_build_args }} \
            -t ${{ vars.CONTAINER_REGISTRY_ENDPOINT }}/${{ inputs.container_name }}:${{ inputs.container_version }}
      
      # Push to container registry
      - name: "Login to Scaleway container registry"
        uses: "docker/login-action@v3"
        with:
          username: "nologin"
          password: "${{ secrets.SCW_SECRET_KEY }}"
          registry: "${{ vars.CONTAINER_REGISTRY_ENDPOINT }}"
      - name: "Push the container image"
        run: "docker push ${{ vars.CONTAINER_REGISTRY_ENDPOINT }}/${{ inputs.container_name }}:${{ inputs.container_version }}"

  deploy:
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Deploy container on Scaleway"
        uses: "scaleway/action-scw@v0.0.3"
        with:
          access-key: "${{ secrets.SCW_ACCESS_KEY }}"
          secret-key: "${{ secrets.SCW_SECRET_KEY }}"
          default-project-id: "${{ vars.SCW_PROJECT_ID }}"
          default-organization-id: "${{ vars.SCW_ORGANIZATION_ID }}"
          args: "container container redeploy ${{ vars.CONTAINER_ID }} region=${{ vars.SCW_REGION }}"
