name: Iconica Standard App CI Action

# Workflow version: 1.0.0

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
    workflow_call:

env:
    PROJECT_ID: ${{ vars.PROJECT_ID }}
    GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ICONICA_ONBOARDING }}
    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    DOTENV_BASE64: ${{ secrets.DOTENV_BASE64 }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                cache: true
                cache-key: ${{ runner.OS }}-flutter-install-cache
            - name: Create dotenv file from GitHub Secrets
              env:
                DOTENV_BASE64: ${{ env.DOTENV_BASE64 }}
              run: echo -n "${DOTENV_BASE64}" | base64 -d > dotenv                      

            - name: Build Flutter Web App
              run: |
                flutter pub get
                flutter build web --release --no-tree-shake-icons
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting --token "${{ env.FIREBASE_TOKEN }}"