name: Iconica Standard App CI Action

# Workflow version: 2.0.0

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
    workflow_call:
      inputs:
        gcp_sa_key_override:
          description: 'Optional GCP Service Account Key Override'
          required: false
          type: string
        use_preview_channel:
          description: 'Deploy to preview channel or live channel'
          required: false
          type: boolean
          default: false
env:
    PROJECT_ID: ${{ vars.PROJECT_ID }}
    GCP_SA_KEY: ${{ secrets[inputs.gcp_sa_key_override || 'GCP_SA_KEY'] }} # Use the override if provided
    DOTENV_BASE64: ${{ secrets.DOTENV_BASE64 }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                cache: true
                cache-key: ${{ runner.OS }}-flutter-install-cache
            - name: Create dotenv file from GitHub Secrets
              env:
                DOTENV_BASE64: ${{ env.DOTENV_BASE64 }}
              run: echo -n "${DOTENV_BASE64}" | base64 -d > dotenv
            - name: Build Flutter Web App
              run: |
                flutter pub get
                flutter build web --release --no-tree-shake-icons
            - name: Determine channel name
              id: channel_name
              run: echo "CHANNEL_NAME=$(echo '${{ github.event.pull_request.title || github.run_id }}' | sed 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_ENV
            - name: Set Deploy Command
              id: deploy-command
              run: echo "DEPLOY_COMMAND=$(if ${{ inputs.use_preview_channel }}; then echo 'hosting:channel:deploy ${CHANNEL_NAME}'; else echo 'deploy --only hosting'; fi)" >> $GITHUB_ENV
              env:
                CHANNEL_NAME: ${{ env.CHANNEL_NAME }}
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: ${{ env.DEPLOY_COMMAND }}
            # - uses: FirebaseExtended/action-hosting-deploy@v0
            #   with:
            #       repoToken: "${{ secrets.GITHUB_TOKEN }}"
            #       firebaseServiceAccount: "${{ env.GCP_SA_KEY }}"
            #       projectId: "${{ env.PROJECT_ID }}"
            #       channelId: live
            #       expires: 2d

