name: Iconica Standard App CI Action

# Workflow version: 2.0.0

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
    workflow_call:
      inputs:
        gcp_sa_key_override:
          description: 'Optional GCP Service Account Key Override'
          required: false
          type: string

env:
    PROJECT_ID: ${{ vars.PROJECT_ID }}
    GCP_SA_KEY: ${{ secrets[inputs.gcp_sa_key_override || 'GCP_SA_KEY'] }} # Use the override if provided
    DOTENV_BASE64: ${{ secrets.DOTENV_BASE64 }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                cache: true
                cache-key: ${{ runner.OS }}-flutter-install-cache
            - name: Create dotenv file from GitHub Secrets
              env:
                DOTENV_BASE64: ${{ env.DOTENV_BASE64 }}
              run: echo -n "${DOTENV_BASE64}" | base64 -d > dotenv
            - name: Build Flutter Web App
              run: |
                flutter pub get
                flutter build web --release --no-tree-shake-icons
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
