name: Iconica Flutter Caching Action

# Workflow version: 2.0.0

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
    workflow_call:

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                cache: true
                cache-key: ${{ runner.OS }}-flutter-install-cache
            - name: Project preparation
              run: flutter pub get