name: Iconica Flutter Caching Action

# Workflow version: 3.0.0

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
    workflow_call:
      inputs:
        subfolder:
          type: string
          description: 'Subfolder where the Flutter project is located'
          required: false
          default: '.'
        flutter_version:
          description: "Optional Flutter Version"
          required: false
          type: string
jobs:
    lint:
        defaults:
          run:
            working-directory: ${{ inputs.subfolder }}
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - name: Flutter install specific version
              if: inputs.flutter_version != ''
              uses: subosito/flutter-action@v2
              with:
                channel: "stable"
                cache: true
                cache-key: ${{ runner.OS }}-flutter-install-cache
                flutter-version: ${{ inputs.flutter_version }}
            - name: Flutter install stable version
              if: inputs.flutter_version == ''
              uses: subosito/flutter-action@v2
              with:
                channel: "stable"
                cache: true
                cache-key: ${{ runner.OS }}-flutter-install-cache
            - name: Project preparation
              run: flutter pub get