name: Iconica Flutter Caching Action

# Workflow version: 1.0.0

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
    workflow_call:

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                    path: |
                        ~/.gradle/wrapper
                        /opt/hostedtoolcache/flutter
                    key: ${{ runner.OS }}-flutter-install-cache
            - uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                cache: true
            - name: Project preparation
              run: flutter pub get