name: Iconica Package Release updater

on:
  workflow_dispatch:

jobs:
    readmeupdate:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - name: Setup Dart
              uses: dart-lang/setup-dart@v1
            - name: Install dependencies
              run: dart pub get --directory=scraper
            - name: Update README.md
              run: |
                cd scraper
                dart main.dart
            - uses: stefanzweifel/git-auto-commit-action@v4
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                    commit_message: "feat: update README.md"
                    branch: master
                    commit_user_name: Github Actions Bot
                    commit_user_email: actions@github.com
                    commit_author: Author <actions@github.com>